function pc_sym = p_com(in1)
%P_COM
%    PC_SYM = P_COM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jun-2019 14:53:03

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
t2 = theta1+theta2+theta3;
t3 = theta1+theta2+theta3+theta4;
t4 = theta1+theta2;
pc_sym = [cos(t2).*(3.0./5.0)+cos(t3)./1.0e1+cos(t4).*(7.0./1.0e1)+cos(theta1).*(9.0./1.0e1);sin(t2).*(3.0./5.0)+sin(t3)./1.0e1+sin(t4).*(7.0./1.0e1)+sin(theta1).*(9.0./1.0e1)];
