function com_Xf_c1 = Xf_1(in1)
%XF_1
%    COM_XF_C1 = XF_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jun-2019 15:06:38

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
t2 = theta1+theta2+theta3;
t3 = theta1+theta2+theta3+theta4;
t4 = theta1+theta2;
t5 = sin(t2);
t6 = sin(t3);
t7 = sin(t4);
t8 = sin(theta1);
t9 = cos(t2);
t10 = t9.*(3.0./5.0);
t11 = cos(t3);
t12 = t11./1.0e1;
t13 = cos(t4);
t14 = t13.*(7.0./1.0e1);
t15 = cos(theta1);
t16 = t15.*(9.0./1.0e1);
com_Xf_c1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,t5.*(3.0./5.0)+t6./1.0e1+t7.*(7.0./1.0e1)+t8.*(9.0./1.0e1),1.0,0.0,0.0,0.0,0.0,-t10-t12-t14-t16-1.0./4.0,0.0,1.0,0.0,t5.*(-3.0./5.0)-t6./1.0e1-t7.*(7.0./1.0e1)-t8.*(9.0./1.0e1),t10+t12+t14+t16+1.0./4.0,0.0,0.0,0.0,1.0],[6,6]);
