function b_cwc_sym = b_cwc(in1)
%B_CWC
%    B_CWC_SYM = B_CWC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Jun-2019 10:22:16

p_com1 = in1(1,:);
b_cwc_sym = [9.81e2./2.5e1;9.81e2./1.25e2;9.81e2./1.25e2;p_com1.*(-9.81e2./2.5e1)+9.81e2./5.0e1;p_com1.*(9.81e2./2.5e1)+9.81e2./5.0e1];
