function H_sym = H(in1)
%H
%    H_SYM = H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-May-2019 16:39:01

theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = sin(theta3);
t3 = cos(theta3);
t4 = t3./2.0;
t5 = t2.^2;
t6 = cos(theta2);
t7 = t3.^2;
t8 = sin(theta2);
t9 = t5+t7+1.0;
t10 = t3+1.0./2.0;
t11 = t3.*t10;
t12 = t4+t5+t7+1.0./2.0;
t13 = t6.*t12;
t16 = (t2.*t8)./2.0;
t14 = t4+t5+t11+t13-t16+6.691666666666667e-1;
t15 = (t3.*t6)./2.0;
t17 = t4+3.345833333333333e-1;
H_sym = reshape([t4+t5+t11+t13+t8.*(t2.*t3-t2.*t10+t8.*t9)-(t2.*t8)./2.0+t6.*(t5+t11+t6.*t9+1.0./2.0)+8.03e2./8.0e2,t14,t4+t15-t16+3.345833333333333e-1,t14,t4+t5+t11+6.691666666666667e-1,t17,t4+t15-(t2.*t8)./2.0+3.345833333333333e-1,t17,3.345833333333333e-1],[3,3]);
