function Jdot_sym = Jdot(in1,in2)
%JDOT
%    JDOT_SYM = JDOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Jun-2019 10:27:29

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta4 = in1(4,:);
theta_dot1 = in2(1,:);
theta_dot2 = in2(2,:);
theta_dot3 = in2(3,:);
theta_dot4 = in2(4,:);
t2 = theta1+theta2;
t3 = cos(t2);
t4 = theta1+theta2+theta3;
t5 = cos(t4);
t6 = theta1+theta2+theta4;
t7 = cos(t6);
t8 = sin(t4);
t9 = sin(t6);
t10 = sin(t2);
Jdot_sym = reshape([t3.*theta_dot1.*(-5.0./8.0)-t3.*theta_dot2.*(5.0./8.0)-(t5.*theta_dot1)./8.0-(t5.*theta_dot2)./8.0-(t5.*theta_dot3)./8.0-(t7.*theta_dot1)./8.0-(t7.*theta_dot2)./8.0-(t7.*theta_dot4)./8.0-theta_dot1.*cos(theta1).*(7.0./8.0),t8.*theta_dot1.*(-1.0./8.0)-(t8.*theta_dot2)./8.0-(t9.*theta_dot1)./8.0-(t8.*theta_dot3)./8.0-(t9.*theta_dot2)./8.0-t10.*theta_dot1.*(5.0./8.0)-t10.*theta_dot2.*(5.0./8.0)-(t9.*theta_dot4)./8.0-theta_dot1.*sin(theta1).*(7.0./8.0),t3.*theta_dot1.*(-5.0./8.0)-t3.*theta_dot2.*(5.0./8.0)-(t5.*theta_dot1)./8.0-(t5.*theta_dot2)./8.0-(t5.*theta_dot3)./8.0-(t7.*theta_dot1)./8.0-(t7.*theta_dot2)./8.0-(t7.*theta_dot4)./8.0,t8.*theta_dot1.*(-1.0./8.0)-(t8.*theta_dot2)./8.0-(t9.*theta_dot1)./8.0-(t8.*theta_dot3)./8.0-(t9.*theta_dot2)./8.0-t10.*theta_dot1.*(5.0./8.0)-t10.*theta_dot2.*(5.0./8.0)-(t9.*theta_dot4)./8.0,t5.*theta_dot1.*(-1.0./8.0)-(t5.*theta_dot2)./8.0-(t5.*theta_dot3)./8.0,t8.*theta_dot1.*(-1.0./8.0)-(t8.*theta_dot2)./8.0-(t8.*theta_dot3)./8.0,t7.*theta_dot1.*(-1.0./8.0)-(t7.*theta_dot2)./8.0-(t7.*theta_dot4)./8.0,t9.*theta_dot1.*(-1.0./8.0)-(t9.*theta_dot2)./8.0-(t9.*theta_dot4)./8.0],[2,4]);
