function vpc_sym = pd_com(in1,in2)
%PD_COM
%    VPC_SYM = PD_COM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-May-2019 09:14:05

theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
theta_dot1 = in2(1,:);
theta_dot2 = in2(2,:);
theta_dot3 = in2(3,:);
t2 = theta1+theta2+theta3;
t3 = sin(t2);
t4 = theta1+theta2;
t5 = sin(t4);
t6 = cos(t4);
t7 = cos(t2);
vpc_sym = [t3.*theta_dot1.*(-1.0./6.0)-(t3.*theta_dot2)./6.0-(t3.*theta_dot3)./6.0-(t5.*theta_dot1)./2.0-(t5.*theta_dot2)./2.0-theta_dot1.*sin(theta1).*(5.0./6.0);(t6.*theta_dot1)./2.0+(t6.*theta_dot2)./2.0+(t7.*theta_dot1)./6.0+(t7.*theta_dot2)./6.0+(t7.*theta_dot3)./6.0+theta_dot1.*cos(theta1).*(5.0./6.0)];
